[phases.setup]
nixPkgs = ['maven', 'jdk17']
nixLibs = []

[phases.build]
cmds = ['cd backend && mvn clean package -DskipTests']

[start]
cmd = 'cd backend && java -jar target/dukanam-backend-0.0.1-SNAPSHOT.jar'
